import type { Metadata } from "next";
import { Jost } from "next/font/google";
import Navbar from "@/components/common/Navbar";
import Providers from "@/components/Providers";
import { Footer } from "@/components/common/Footer";

import "./globals.css";

const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Owltlet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`relative h-full ${jost.className} dark:bg-dark-bg`}>
        <Providers>
          <main className="flex flex-col relative min-h-screen bg-light-bg dark:bg-dark-bg ">
            <Navbar/>
            <div className="flex-grow flex-1">{children}</div>
          </main>
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
